name: Get latest flexget version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Setup Git User
        run: |
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/Flexget/Flexget/tags | \
          jq -r ".[0].name" | \
          sed "s/^v//" > flexget-latest-version
      - name: Update FLEXGET_VERSION in Dockerfile
        run: |
          VERSION=$(cat flexget-latest-version)
          sed -i "s/^ARG FLEXGET_VERSION=.*/ARG FLEXGET_VERSION=$VERSION/" Dockerfile
      - name: Commit latest release version
        run: |
          git diff --exit-code || git commit -am "Auto: update Flexget version" && git push
