name: Get latest flexget version

on:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Setup Git User
        run: |
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/Flexget/Flexget/tags | \
          jq -r ".[0].name" | \
          sed "s/^v//" > flexget-latest-version
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "Auto: update Flexget version"
          git push
